apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-latest-tag
spec:
  validationFailureAction: Audit
  rules:
    - name: block-latest-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Using ':latest' tag is not allowed. Use a specific commit SHA tag."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
