apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/racenak/mlops-k8s-deployment
    targetRevision: test-argocd
    path: apps/hello-argocd/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
