apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argocd
  labels:
    app: hello-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-argocd
  template:
    metadata:
      labels:
        app: hello-argocd
    spec:
      containers:
        - name: hello-argocd
          image: ghcr.io/racenak/mlops-k8s-deployment/hello-argocd:c7bfaa884607a38304c4c3c1995cdec4a2792fc5
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          resources:
            requests:
              cpu: 50m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
