apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-argocd
  namespace: default
spec:
  hosts:
    - hello-argocd
  http:
    - route:
        - destination:
            host: hello-argocd
            subset: stable
            port:
              number: 8080
          weight: 90
        - destination:
            host: hello-argocd
            subset: canary
            port:
              number: 8080
          weight: 10