apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../base

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          argocd: "true"

  - target:
      kind: StatefulSet
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          argocd: "true"