apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install.yaml
  - ../policies/require-labels.yaml
  - ../policies/restrict-latest-tag.yaml
  - ../policies/require-resource-limits.yaml
